version: '3.4'

services:

  #CLIENT

  discountmanager-client:
    build:
      context: .
      dockerfile: DiscountManager.Client/Dockerfile
    container_name: discountmanager-client
    networks:
      - discountmanager-network
    stdin_open: true 
    tty: true

  #SERVICE

  discountmanager-server:
    container_name: discountmanager-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - discount-manager-mongodb
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - discountmanager-network

  #DATABASES

  discount-manager-mongodb:
    container_name: discount-manager-mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/data/discount-manager-mongodb
    networks:
      - discountmanager-network

networks:
  discountmanager-network:
    driver: bridge